Repository thesofproject/linux, pull requests merged in 2019-06, with the labels that each got.

#983 Enable WAKEEN feature in sof hda driver
  sound/soc/sof/intel/hda-codec.c
  sound/soc/sof/intel/hda-dsp.c
  sound/soc/sof/intel/hda.h
Labels: Unclear

#991 ASoC: SOF: Add DMIC token for unmute gain ramp time
  include/sound/sof/dai-intel.h
  include/uapi/sound/sof/abi.h
  include/uapi/sound/sof/tokens.h
  sound/soc/sof/topology.c
Labels: ABI

#1024 ASoC: codec: hdac_hdmi: fix pin connections at cvt enable
  sound/soc/codecs/hdac_hdmi.c
Labels: upstream

#1035 ASoC: Intel: sof-rt5682: correct naming for dmic16k
  sound/soc/intel/boards/sof_rt5682.c
Labels: upstream

#1033 ASoC: Intel: sof-rt5682: add MCLK support for BYT platform
  sound/soc/intel/boards/sof_rt5682.c
Labels: upstream
